// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"im/api/pb"
	"im/internal/transfer/data"
	"im/internal/transfer/service"
	"im/pkg/rabbitmq"
)

// Injectors from wire.go:

func wireApp(pbData *pb.Data, logger log.Logger) (*service.TransferService, error) {
	rabbitmqRabbitmq, err := rabbitmq.NewRabbitmq(pbData)
	if err != nil {
		return nil, err
	}
	msgRabbitmq := rabbitmq.NewMsgRabbitmq(rabbitmqRabbitmq, pbData)
	dataData := data.NewData(msgRabbitmq, logger)
	transferService := service.NewPushService(logger, dataData)
	return transferService, nil
}
