// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"im/api/pb"
	"im/internal/logic/data"
	"im/internal/logic/server"
	"im/internal/logic/service"
	"im/pkg/etcd"
)

// Injectors from wire.go:

func wireApp(logicConfig *pb.LogicConfig, pbData *pb.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysql(pbData)
	client := data.NewRedis(pbData)
	discovery := etcd.NewDiscovery(pbData)
	gateWayClient := data.NewGetWayServiceClient(discovery)
	dataData := data.NewData(db, client, gateWayClient)
	logicRepo := data.NewLogicRepo(dataData)
	logicService := service.NewLogicService(logicRepo)
	grpcServer := server.NewGRPCServer(logicConfig, logicService)
	registrar := etcd.NewRegister(pbData)
	app := newApp(grpcServer, logger, registrar)
	return app, func() {
	}, nil
}
