server:
  gateway:
    http:
      addr: 0.0.0.0:9990
      timeout: 1s
    ws:
      readBufferSize: 1024
      writeBufferSize: 65536
      handshakeTimeout: 10
    grpc:
      addr: 0.0.0.0:9991
      timeout: 1s
  logic:
    grpc:
      addr: 0.0.0.0:9992
      timeout: 1s
  msg:
    grpc:
      addr: 0.0.0.0:9993
      timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(192.168.0.99:3306)/im?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    address: 192.168.0.99:6379
  etcd:
    address: 192.168.0.99:2379
  rabbitmq:
    address: amqp://guest:guest@192.168.0.99:5673
    exchangeName: msgToMq
    queueName: msgToMq
    key: msgToMq
log:
  fileName: ./logger/im.log
  maxSize: 500
  maxBackups: 1
  maxAge: 7

