// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package pb

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsMsgSend(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MSG_SEND.String() && e.Code == 402
}

func ErrorMsgSend(format string, args ...interface{}) *errors.Error {
	return errors.New(402, ErrorReason_MSG_SEND.String(), fmt.Sprintf(format, args...))
}
