// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: logic.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddFriendReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddFriendReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddFriendReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddFriendReqMultiError, or
// nil if none found.
func (m *AddFriendReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddFriendReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FriendId

	// no validation rules for Remarks

	// no validation rules for Description

	if len(errors) > 0 {
		return AddFriendReqMultiError(errors)
	}

	return nil
}

// AddFriendReqMultiError is an error wrapping multiple validation errors
// returned by AddFriendReq.ValidateAll() if the designated constraints aren't met.
type AddFriendReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddFriendReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddFriendReqMultiError) AllErrors() []error { return m }

// AddFriendReqValidationError is the validation error returned by
// AddFriendReq.Validate if the designated constraints aren't met.
type AddFriendReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddFriendReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddFriendReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddFriendReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddFriendReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddFriendReqValidationError) ErrorName() string { return "AddFriendReqValidationError" }

// Error satisfies the builtin error interface
func (e AddFriendReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddFriendReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddFriendReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddFriendReqValidationError{}

// Validate checks the field values on AddFriendResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddFriendResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddFriendResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddFriendRespMultiError, or
// nil if none found.
func (m *AddFriendResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AddFriendResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AddFriendRespMultiError(errors)
	}

	return nil
}

// AddFriendRespMultiError is an error wrapping multiple validation errors
// returned by AddFriendResp.ValidateAll() if the designated constraints
// aren't met.
type AddFriendRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddFriendRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddFriendRespMultiError) AllErrors() []error { return m }

// AddFriendRespValidationError is the validation error returned by
// AddFriendResp.Validate if the designated constraints aren't met.
type AddFriendRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddFriendRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddFriendRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddFriendRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddFriendRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddFriendRespValidationError) ErrorName() string { return "AddFriendRespValidationError" }

// Error satisfies the builtin error interface
func (e AddFriendRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddFriendResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddFriendRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddFriendRespValidationError{}
