// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: msg.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendMsgReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendMsgReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMsgReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendMsgReqMultiError, or
// nil if none found.
func (m *SendMsgReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMsgReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMsg()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendMsgReqValidationError{
					field:  "Msg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendMsgReqValidationError{
					field:  "Msg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMsg()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendMsgReqValidationError{
				field:  "Msg",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SendMsgReqMultiError(errors)
	}

	return nil
}

// SendMsgReqMultiError is an error wrapping multiple validation errors
// returned by SendMsgReq.ValidateAll() if the designated constraints aren't met.
type SendMsgReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMsgReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMsgReqMultiError) AllErrors() []error { return m }

// SendMsgReqValidationError is the validation error returned by
// SendMsgReq.Validate if the designated constraints aren't met.
type SendMsgReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMsgReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMsgReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMsgReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMsgReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMsgReqValidationError) ErrorName() string { return "SendMsgReqValidationError" }

// Error satisfies the builtin error interface
func (e SendMsgReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMsgReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMsgReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMsgReqValidationError{}

// Validate checks the field values on SendMsgResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendMsgResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMsgResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendMsgRespMultiError, or
// nil if none found.
func (m *SendMsgResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMsgResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SendMsgRespMultiError(errors)
	}

	return nil
}

// SendMsgRespMultiError is an error wrapping multiple validation errors
// returned by SendMsgResp.ValidateAll() if the designated constraints aren't met.
type SendMsgRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMsgRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMsgRespMultiError) AllErrors() []error { return m }

// SendMsgRespValidationError is the validation error returned by
// SendMsgResp.Validate if the designated constraints aren't met.
type SendMsgRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMsgRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMsgRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMsgRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMsgRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMsgRespValidationError) ErrorName() string { return "SendMsgRespValidationError" }

// Error satisfies the builtin error interface
func (e SendMsgRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMsgResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMsgRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMsgRespValidationError{}
